      - name: checkout repo
        uses: actions/checkout@v4
        with:
          ref: "${{ github.event.inputs.branch }}"

      - name: set ansible var file for dev
        run: |
          echo "ANSIBLE_VAR_FILE=${{ env.ansible_var_file }}" >> $GITHUB_ENV
          echo "SSH_KEY_FILE=${{ env.key_name }}" >> $GITHUB_ENV

      - name: Configure AWS Credentials
        id: creds
        uses: aws-actions/configure-aws-credentials@v4
        with:
          aws-region: "${{ env.region }}"
          role-to-assume: "${{ env.aws_role_arn }}"
          output-credentials: true

      - name: download key file
        uses: keithweaver/aws-s3-github-action@v1.0.0
        with:
          command: cp
          source: s3://ds-dev-kpf-administration/discovery/${{ env.key_name }}
          destination: ./${{ env.key_name }}
          aws_access_key_id: ${{ steps.creds.outputs.aws-access-key-id }}
          aws_secret_access_key: ${{ steps.creds.outputs.aws-secret-access-key }}
          aws_session_token: ${{ steps.creds.outputs.aws-session-token }}
          aws_region: ${{ env.region }}

      - name: install python
        uses: actions/setup-python@v5
        with:
          python-version: '3.11'
          cache: 'pip'
          cache-dependency-path: '**/discovery-req.txt'
      - run: pip install -r ${{ github.workspace }}/.github/workflows/discovery-req.txt

      - name: install ansible.windows
        run: ansible-galaxy collection install ansible.windows

      - name: run ansible playbook
        env:
          AWS_ROLE_ARN: "arn:aws:iam::846769538626:role/s-devops-ansible-amis"
          VPC_ID: ${{ secrets.VPC_ID }}
          SUBNET_ID: ${{ secrets.SUBNET_ID }}
        run: |
          cur_dir=$(pwd)
          cd $cur_dir/discovery/web-wincore
          export AWS_ACCESS_KEY_ID=${{ steps.creds.outputs.aws-access-key-id }}
          export AWS_SECRET_ACCESS_KEY=${{ steps.creds.outputs.aws-secret-access-key }}
          export AWS_SESSION_TOKEN=${{ steps.creds.outputs.aws-session-token }}
          export AWS_DEFAULT_REGION="${{ env.region }}"
          ansible-playbook \
          --extra-vars "ansible_var_file=${{ env.ANSIBLE_VAR_FILE }} key_name=${{ env.key_name }} region=${{ env.region }} env=${{ github.event.inputs.deploy-environment }}" \
          --private-key $cur_dir/${{ env.SSH_KEY_FILE }} \
          discovery-web-wincore-playbook.yml
