---
name: Discovery App Wincore AMI

permissions:
  id-token: write
  contents: write

on:
  workflow_dispatch:
    inputs:
      account:
        type: choice
        description: AWS Account
        required: true
        options:
        - dev
        - staging
        - live

jobs:
# ------------------------------------------------------------------------------
# dev deployment
# ------------------------------------------------------------------------------
  discovery-api-wincore-ami-dev:
    if: github.event.inputs.account == 'dev'
    uses: nationalarchives/ds-github-actions/.github/workflows/discovery-app-wincore.yml@split-discovery-workflows
    with:
      region: "eu-west-2"
      key_name: "discovery-app-${{ github.event.inputs.account }}-eu-west-2"
      base_role: "arn:aws:iam::846769538626:role/GithubOIDCProviderIAMRolePermissions-Role-I80RXHT6O1PL"
      playbook_role: "arn:aws:iam::846769538626:role/s-devops-ansible-amis"
      instance_type": "t3a.medium"
      volume_size": 40
      s3_deployment_bucket: "ds-intersite-deployment"
      s3_deployment_root: "discovery/installation-packages"
      account: "${{ github.event.inputs.account }}"
      branch: "${{ github.event.inputs.branch }}"
    secrets:
      vpc_id: ${{ secrets.VPC_ID_DEV }}
      subnet_id: ${{ secrets.SUBNET_ID_2A_DEV }}

# ------------------------------------------------------------------------------
# staging deployment
# ------------------------------------------------------------------------------
  discovery-api-wincore-ami-staging:
    if: github.event.inputs.account == 'staging'
    uses: nationalarchives/ds-github-actions/.github/workflows/discovery-app-wincore.yml@main
    with:
      region: "eu-west-2"
      key_name: "discovery-app-${{ github.event.inputs.account }}-eu-west-2"
      base_role: "arn:aws:iam::337670467269:role/GitHubActionRole"
      playbook_role: "arn:aws:iam::337670467269:role/s-devops-ansible-amis"
      instance_type": "t3a.large"
      volume_size": 80
      s3_deployment_bucket: "ds-intersite-deployment"
      s3_deployment_root: "discovery/installation-packages"
      account: "${{ github.event.inputs.account }}"
      branch: "${{ github.event.inputs.branch }}"
    secrets:
      vpc_id: ${{ secrets.VPC_ID_STAGING }}
      subnet_id: ${{ secrets.SUBNET_ID_2A_STAGING }}

# ------------------------------------------------------------------------------
# live deployment
# ------------------------------------------------------------------------------
  discovery-api-wincore-ami-live:
    if: github.event.inputs.account == 'live'
    uses: nationalarchives/ds-github-actions/.github/workflows/discovery-app-wincore.yml@main
    with:
      region: "eu-west-2"
      key_name: "discovery-app-${{ github.event.inputs.account }}-eu-west-2"
      base_role: "arn:aws:iam::968803923593:role/github-oidc-Role-1QSZDDE2NZQV0"
      playbook_role: "arn:aws:iam::968803923593:role/s-devops-ansible-amis"
      instance_type": "t3a.large"
      volume_size": 100
      s3_deployment_bucket: "ds-intersite-deployment"
      s3_deployment_root: "discovery/installation-packages"
      account: "${{ github.event.inputs.account }}"
      branch: "${{ github.event.inputs.branch }}"
    secrets:
      vpc_id: ${{ secrets.VPC_ID_LIVE }}
      subnet_id: ${{ secrets.SUBNET_ID_2A_LIVE }}
...
