name: Taxonomy Updater AMI

permissions:
  id-token: write
  contents: write

on:
  workflow_dispatch:
    inputs:
      deploy-environment:
        type: choice
        description: Environment
        required: true
        options:
          - staging
          - dev

jobs:
  # ------------------------------------------------------------------------------
  # dev deployment
  # ------------------------------------------------------------------------------
  taxonomy-updater-ami-dev:
    if: github.event.inputs.deploy-environment == 'dev'
    uses: nationalarchives/ds-github-actions/.github/workflows/taxonomy-indexer.yml@main
    with:
      region: "eu-west-2"
      key_name: "taxonomy-updater-${{ github.event.inputs.account }}-eu-west-2"
      base_role: "arn:aws:iam::846769538626:role/GithubOIDCProviderIAMRolePermissions-Role-I80RXHT6O1PL"
      playbook_role: "arn:aws:iam::846769538626:role/s-devops-ansible-amis"
      instance_type: "t3a.medium"
      volume_size: 40
      s3_deployment_bucket: "ds-dev-deployment-source"
      s3_deployment_root: "taxonomy/installation-packages"
      account: "${{ github.event.inputs.account }}"
      branch: "${{ github.event.inputs.branch }}"
    secrets:
      vpc_id: ${{ secrets.VPC_ID_DEV }}
      subnet_id: ${{ secrets.SUBNET_ID_2A_DEV }}

  # ------------------------------------------------------------------------------
  # staging deployment
  # ------------------------------------------------------------------------------
  taxonomy-updater-ami-staging:
    if: github.event.inputs.deploy-environment == 'staging'
    uses: nationalarchives/ds-github-actions/.github/workflows/taxonomy-indexer.yml@main
    with:
      region: "eu-west-2"
      key_name: "taxonomy-updater-${{ github.event.inputs.account }}-eu-west-2"
      base_role: "arn:aws:iam::337670467269:role/GitHubActionRole"
      playbook_role: "arn:aws:iam::337670467269:role/s-devops-ansible-amis"
      instance_type: "t3a.large"
      volume_size: 40
      s3_deployment_bucket: "ds-staging-deployment-source"
      s3_deployment_root: "taxonomy/installation-packages"
      account: "${{ github.event.inputs.account }}"
      branch: "${{ github.event.inputs.branch }}"
    secrets:
      vpc_id: ${{ secrets.VPC_ID_STAGING }}
      subnet_id: ${{ secrets.SUBNET_ID_2A_STAGING }}
...
