# Deploy Website NginX Frontend AMI

name: Create Website NginX Frontend

permissions:
  id-token: write
  contents: write 

on:
  workflow_dispatch:
    inputs:
      deploy-environment:
        type: choice
        description: Environment
        options: 
        - dev
        - test
        - live

jobs:
  ami-deployment:
    runs-on: ubuntu-latest
    steps:
      - name: set ansible var file for dev
        if: github.event.inputs.deploy-environment == 'dev'
        run: echo "ANSIBLE_VAR_FILE=vars_dev.yml" >> $GITHUB_ENV
      - name: set ansible var file for test
        if: github.event.inputs.deploy-environment == 'test'
        run: echo "ANSIBLE_VAR_FILE=vars_test.yml" >> $GITHUB_ENV   
      - name: output environment details
        if: github.event.inputs.deploy-environment == 'test'
        run: |
          echo ${{ github.event.inputs.deploy-environment }}    
          echo ${{ env.ANSIBLE_VAR_FILE }}    
