# Deploy Website NginX Frontend AMI

name: Create Website NginX Frontend

permissions:
  id-token: write
  contents: write 

on:
  workflow_dispatch:
    inputs:
      environment:
        type: environment

jobs:
  ami-deployment-dev:
    runs-on: ubuntu-latest
    environment: dev
    steps:
      - name: set ansible var file for dev
        run: echo "ANSIBLE_VAR_FILE=vars_dev.yml" >> $GITHUB_ENV
      - name: output environment details
        run: |
          echo "dev"
          echo ${{ github.event.inputs.deploy-environment }}    
          echo ${{ env.ANSIBLE_VAR_FILE }}    
  ami-deployment-staging:
    runs-on: ubuntu-latest
    environment: staging
    steps:
      - name: set ansible var file for test
        run: echo "ANSIBLE_VAR_FILE=vars_test.yml" >> $GITHUB_ENV    
      - name: output environment details
        run: |
          echo "Staging"
          echo ${{ github.event.inputs.deploy-environment }}    
          echo ${{ env.ANSIBLE_VAR_FILE }}    
