# Deploy Website NginX Frontend AMI

name: Create Website NginX Frontend

permissions:
  id-token: write
  contents: write

on:
  workflow_dispatch:
    inputs:
      deploy-environment:
        type: choice
        description: Environment
        required: true
        options:
        - dev
        - staging
        - production

jobs:
  ami-deployment-dev:
    if: github.event.inputs.deploy-environment == 'dev'
    runs-on: ubuntu-latest
    environment: dev
    steps:
      - name: checkout repo
        uses: actions/checkout@v1

      - name: set ansible var file for dev
        run: |
          echo "ANSIBLE_VAR_FILE=vars_dev.yml" >> $GITHUB_ENV
          echo "SSH_KEY_FILE=wp-app-dev-london.pem" >> $GITHUB_ENV

      - name: aws variable settings
        run: |
          echo AWS_ROLE_ARN=${{ secrets.AWS_ROLE_ARN }} >> $GITHUB_ENV
          echo AWS_DEFAULT_REGION=eu-west-2 >> $GITHUB_ENV
          echo AWS_ACCESS_KEY_ID=${{ secrets.AWS_ACCESS_KEY_ID }} >> $GITHUB_ENV
          echo AWS_SECRET_ACCESS_KEY=${{ secrets.AWS_SECRET_ACCESS_KEY }} >> $GITHUB_ENV

      - name: write ssh key file
        run: echo "${{ secrets.SSH_KEY }}" | tr -d '\r' > ${{ env.SSH_KEY_FILE }}

#      - name: install aws cli
##        run: |
#          #curl -H "Authorization: bearer $ACTIONS_ID_TOKEN_REQUEST_TOKEN" "$ACTIONS_ID_TOKEN_REQUEST_URL" | jq -r '.value' > $AWS_WEB_IDENTITY_TOKEN_FILE
#          sudo apt-get install awscli
      - name: install python
        uses: actions/setup-python@v2
        with:
          python-version: 3
      - name: upgrade pip
        run: pip install --upgrade pip
      - name: install aws cli
        run: sudo apt-get install awscli
      - name: install boto3
        run: pip3 install boto3 requests pyjwt
      - name: install wheel
        run: pip3 install wheel requests pyjwt
      - name: install ansible
        run: pip3 install ansible

      - name: set aws creds
        run: |
          mkdir ~/.aws
          touch ~/.aws/credentials
          echo [default] >> ~/.aws/credentials
          echo AWS_ACCESS_KEY_ID = ${{ secrets.AWS_ACCESS_KEY_ID }} >> ~/.aws/credentials
          echo AWS_SECRET_ACCESS_KEY = ${{ secrets.AWS_SECRET_ACCESS_KEY }} >> ~/.aws/credentials
          touch ~/.aws/config
          echo [default] >> ~/.aws/config
          echo region = eu-west-2 >> ~/.aws/config
          echo output = json >> ~/.aws/config
          echo >> ~/.aws/config
          echo [profile s-devops] >> ~/.aws/config
          echo role_arn = ${{ secrets.AWS_ROLE_ARN }} >> ~/.aws/config
          echo source_profile = default >> ~/.aws/config
          echo region = eu-west-2 >> ~/.aws/config
          echo output = json >> ~/.aws/config

      - name: run ansible playbook
        env:
          AWS_ROLE_ARN: ${{ secrets.AWS_ROLE_ARN }}
        run: |
          cur_dir=$(pwd)
          cd $cur_dir/wp-website/nginx
          ansible-playbook --extra-vars ${{ env.ANSIBLE_VAR_FILE }} --private-key $cur_dir/${{ env.SSH_KEY_FILE }} -vvv nginx-playbook.yml

  ami-deployment-staging:
    if: github.event.inputs.deploy-environment == 'staging'
    runs-on: ubuntu-latest
    environment: staging
    steps:
      - name: set ansible var file for test
        run: echo "ANSIBLE_VAR_FILE=vars_test.yml" >> $GITHUB_ENV
      - name: output environment details
        run: |
          echo "Staging"
          echo ${{ github.event.inputs.deploy-environment }}
          echo ${{ env.ANSIBLE_VAR_FILE }}
