# Deploy Website NginX Frontend AMI

name: Create Website NginX Frontend

permissions:
  id-token: write
  contents: write

on:
  workflow_dispatch:
    inputs:
      deploy-environment:
        type: choice
        description: Environment
        options:
        - dev
        - staging
        - production

jobs:
  ami-deployment-dev:
    if: github.event.inputs.deploy-environment == 'dev'
    runs-on: ubuntu-latest
    environment: dev
    steps:
      - name: checkout repo
        uses: actions/checkout@v1

      - name: set ansible var file for dev
        run: |
          echo "ANSIBLE_VAR_FILE=vars_dev.yml" >> $GITHUB_ENV
          echo "SSH_KEY_FILE=wp-app-dev-london.pem" >> $GITHUB_ENV

      - name: aws variable settings
        run: |
          echo AWS_ROLE_ARN=${{ secrets.AWS_ROLE_ARN }} >> $GITHUB_ENV
          echo AWS_DEFAULT_REGION=eu-west-2 >> $GITHUB_ENV
          echo AWS_ACCESS_KEY_ID=${{ secrets.AWS_ACCESS_KEY_ID }} >> $GITHUB_ENV
          echo AWS_SECRET_ACCESS_KEY=${{ secrets.AWS_SECRET_ACCESS_KEY }} >> $GITHUB_ENV

      - name: write ssh key file
        run: echo "${{ secrets.SSH_KEY }}" | tr -d '\r' > ${{ env.SSH_KEY_FILE }}

#      - name: install aws cli
##        run: |
#          #curl -H "Authorization: bearer $ACTIONS_ID_TOKEN_REQUEST_TOKEN" "$ACTIONS_ID_TOKEN_REQUEST_URL" | jq -r '.value' > $AWS_WEB_IDENTITY_TOKEN_FILE
#          sudo apt-get install awscli

      - name: install ansible
        run: |
          sudo apt-get install ansible

      - name: run ansible playbook
        run: |
          cur_dir=$(pwd)
          cd $cur_dir/wp-website/nginx
          echo AWS_ACCESS_KEY_ID: "${{ secrets.AWS_ACCESS_KEY_ID }}" >> $cur_dir/wp-website/nginx/${{ env.ANSIBLE_VAR_FILE }}
          echo AWS_SECRET_ACCESS_KEY: "${{ secrets.AWS_SECRET_ACCESS_KEY }}" >> $cur_dir/wp-website/nginx/${{ env.ANSIBLE_VAR_FILE }}
          echo role_arn: "${{ secrets.AWS_ROLE_ARN }}" >> $cur_dir/wp-website/nginx/${{ env.ANSIBLE_VAR_FILE }}
          ansible-playbook --extra-vars ${{ env.ANSIBLE_VAR_FILE }} --private-key $cur_dir/${{ env.SSH_KEY_FILE }} -vvv nginx-playbook.yml

  ami-deployment-staging:
    if: github.event.inputs.deploy-environment == 'staging'
    runs-on: ubuntu-latest
    environment: staging
    steps:
      - name: set ansible var file for test
        run: echo "ANSIBLE_VAR_FILE=vars_test.yml" >> $GITHUB_ENV
      - name: output environment details
        run: |
          echo "Staging"
          echo ${{ github.event.inputs.deploy-environment }}
          echo ${{ env.ANSIBLE_VAR_FILE }}
