# This is a basic workflow to help you get started with Actions

name: Create Website NginX Frontend

permissions:
  id-token: write
  contents: write 

on:
  workflow_dispatch:
    inputs:
      deploy-environment:
        type: choice
        description: Environment
        options: 
        - dev
        - test
        - live

# A workflow run is made up of one or more jobs that can run sequentially or in parallel
jobs:
  create-ami:
    runs-on: ubuntu-latest
    steps:
      - name: output dev
        run: echo ${{ github.event.inputs.deploy-environment }}
        if: github.event.inputs.deploy-environment == 'dev'
      - name: output test
        run: echo ${{ github.event.inputs.deploy-environment }}
        if: github.event.inputs.deploy-environment == 'test'
    
